export const planets = [
  {
    name: "Mercury",
    texture: "/assets/textures/mercury.jpg",
    radius: 0.4,
    distance: 8,
    orbitalPeriod: 88,
    rotationSpeed: 0.004,
  },
  {
    name: "Venus",
    texture: "/assets/textures/venus.jpg",
    radius: 0.8,
    distance: 11,
    orbitalPeriod: 225,
    rotationSpeed: 0.002,
  },
  {
    name: "Earth",
    texture: "/assets/textures/earth.jpg",
    radius: 1,
    distance: 14,
    orbitalPeriod: 365,
    rotationSpeed: 0.02,
  },
  {
    name: "Mars",
    texture: "/assets/textures/mars.jpg",
    radius: 0.6,
    distance: 17,
    orbitalPeriod: 687,
    rotationSpeed: 0.018,
  },
  {
    name: "Jupiter",
    texture: "/assets/textures/jupiter.jpg",
    radius: 1.8,
    distance: 23,
    orbitalPeriod: 4331,
    rotationSpeed: 0.04,
  },
  {
    name: "Saturn",
    texture: "/assets/textures/saturn.jpg",
    radius: 1.6,
    distance: 29,
    orbitalPeriod: 10747,
    rotationSpeed: 0.038
  },
  {
    name: "Uranus",
    texture: "/assets/textures/uranus.jpg",
    radius: 1.3,
    distance: 35,
    orbitalPeriod: 30589,
    rotationSpeed: 0.03,
  },
  {
    name: "Neptune",
    texture: "/assets/textures/neptune.jpg",
    radius: 1.2,
    distance: 41,
    orbitalPeriod: 59800,
    rotationSpeed: 0.028,
  },
];
